### ISSUE TITLE
error while create new world

### ISSUE THREAD

**Issue by Szybkimp3** [Fenixin/Minecraft-Region-Fixer#181]
[17:05:04] [Server thread/INFO]: Szybkimp3 issued server command: /mv create rtvt normal
[17:05:04] [Server thread/INFO]: Szybkimp3: Starting creation of world 'rtvt'...
[17:05:04] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'rtvt' - Env: NORMAL - Type: NORMAL
[17:05:04] [Server thread/WARN]: com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
[17:05:04] [Server thread/WARN]: at net.minecraft.util.ChatDeserializer.a(ChatDeserializer.java:505)
[17:05:04] [Server thread/WARN]: at net.minecraft.util.ChatDeserializer.a(ChatDeserializer.java:555)
[17:05:04] [Server thread/WARN]: at net.minecraft.util.ChatDeserializer.a(ChatDeserializer.java:551)
[17:05:04] [Server thread/WARN]: at net.minecraft.util.ChatDeserializer.a(ChatDeserializer.java:559)
[17:05:04] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.createWorld(CraftServer.java:1198)
[17:05:04] [Server thread/WARN]: at org.bukkit.Bukkit.createWorld(Bukkit.java:767)
[17:05:04] [Server thread/WARN]: at org.bukkit.WorldCreator.createWorld(WorldCreator.java:466)
[17:05:04] [Server thread/WARN]: at Multiverse-Core-4.3.2-SNAPSHOT.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[17:05:04] [Server thread/WARN]: at Multiverse-Core-4.3.2-SNAPSHOT.jar//com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:288)
[17:05:04] [Server thread/WARN]: at Multiverse-Core-4.3.2-SNAPSHOT.jar//com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:125)
[17:05:04] [Server thread/WARN]: at Multiverse-Core-4.3.2-SNAPSHOT.jar//com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
[17:05:04] [Server thread/WARN]: at Multiverse-Core-4.3.2-SNAPSHOT.jar//com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[17:05:04] [Server thread/WARN]: at Multiverse-Core-4.3.2-SNAPSHOT.jar//com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[17:05:04] [Server thread/WARN]: at Multiverse-Core-4.3.2-SNAPSHOT.jar//com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
[17:05:04] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:05:04] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[17:05:04] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2380)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2191)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2172)
[17:05:04] [Server thread/WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[17:05:04] [Server thread/WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[17:05:04] [Server thread/WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:05:04] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:05:04] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1416)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[17:05:04] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1393)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1386)
[17:05:04] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1364)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1251)
[17:05:04] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[17:05:04] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[17:05:04] [Server thread/WARN]: Caused by: java.io.EOFException: End of input at line 1 column 1 path $
[17:05:04] [Server thread/WARN]: at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395)
[17:05:04] [Server thread/WARN]: at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548)
[17:05:04] [Server thread/WARN]: at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
[17:05:04] [Server thread/WARN]: at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661)
[17:05:04] [Server thread/WARN]: at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
[17:05:04] [Server thread/WARN]: at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
[17:05:04] [Server thread/WARN]: at net.minecraft.util.ChatDeserializer.a(ChatDeserializer.java:503)
[17:05:04] [Server thread/WARN]: ... 35 more
[17:05:04] [Server thread/ERROR]: [Multiverse-Core] The world 'rtvt' could NOT be loaded because it contains errors and is probably corrupt!
[17:05:04] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'rtvt'
[17:05:04] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[17:05:04] [Server thread/ERROR]: [Multiverse-Core] Failed to Create/Load the world 'rtvt'
[17:05:04] [Server thread/INFO]: Szybkimp3: FAILED.

**Comment by Fenixin** [comment]
Hello!

This is not regionfixer related. The world creator points to regionfixer but you haven't run it and don't provide any insight about what's the problem.

I'm going to close the issue. If you try regionfixer and find a problem, please, don't hesistate to ask if you need help.
