### ISSUE TITLE
Bug: python traceback when deleting entities

### ISSUE THREAD

**Issue by ghost** [Fenixin/Minecraft-Region-Fixer#28]
Command used:

```
region-fixer.exe --delete-entities Desktop\world
```

Yes, the server is on Windows... (it's for my brother)

Output:

```
Welcome to Region Fixer!
(version: 0.1.2)

############################################################
#################  Scanning world: world  ##################
############################################################

Scanning directory...
There are 79 region files and 6 player files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

------------------ Checking player files -------------------
All player files are readable.

------------------ Scanning the Overworld ------------------
Traceback (most recent call last):                             ] ETA:  00:01:13
  File "region-fixer.py", line 304, in <module>
  File "region-fixer.py", line 226, in main
  File "scan.pyc", line 112, in scan_world
  File "scan.pyc", line 406, in scan_regionset
  File "multiprocessing\queues.pyc", line 376, in get
TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'nbt.region
.ChunkDataError'>, ())
```

This seems to me like a definite bug in the code – wrong number of parameters given.

Also, the problem I am actually trying to fix is that there are thousands of duplicate horses (with the same name) that make the server glitch out and crash with heaps of messages about wrong location, so I would appreciate advice on fixing that too.

**Comment by Fenixin** [comment]
This is very outdated and a lot has changed since 2013.

I'm closing this issue, feel free to open a new one if you have problems.
