### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 0

### ISSUE THREAD

**Issue by elderlabs** [Fenixin/Minecraft-Region-Fixer#54]
``` <type 'exceptions.UnicodeEncodeError'>
Traceback (most recent call last):
  File "/srv/scripts/Minecraft-Region-Fixer/Minecraft-Region-Fixer/regionfixer.py", line 506, in <module>
    value = main()
  File "/srv/scripts/Minecraft-Region-Fixer/Minecraft-Region-Fixer/regionfixer.py", line 404, in main
    print(entitle(' Scanning world: {0} '.format(w_name), 0))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 0: ordinal not in range(128)
```

**Comment by Fenixin** [comment]
This is pretty outdated and a lot has changed since then, I'm going to close this.

Please, feel free to open a new issue if you find this problem again or reopen this if you have new information to provide.

**Comment by elderlabs** [comment]
This is an old one. Regardless, I've found new employment since then, so this no longer affects me.
