### ISSUE TITLE
No world paths or region files specified

### ISSUE THREAD

**Issue by DimensionSponge** [Fenixin/Minecraft-Region-Fixer#85]
Trying to scan a world and it says I didn't specify a worldpath even when I did. Maybe I'm just doing it wrong. It does the same thing when I try to use the help command also. Using python 3.7.3

C:\Users\lilli\Downloads\Minecraft-Region-Fixer-0.3.1\Minecraft-Region-Fixer-0.3.1>regionfixer.py C:\Users\lilli\AppData\Roaming\.minecraft\saves\Copy of 29 4 19 tired
Usage:
region_fixer [options] <world-path> <other-world-path> ... <region-files> ...

region_fixer: error: No world paths or region files specified! Use --help for a complete list of options.
Traceback (most recent call last):
  File "C:\Users\lilli\Downloads\Minecraft-Region-Fixer-0.3.1\Minecraft-Region-Fixer-0.3.1\regionfixer.py", line 560, in <module>
    value = main()
  File "C:\Users\lilli\Downloads\Minecraft-Region-Fixer-0.3.1\Minecraft-Region-Fixer-0.3.1\regionfixer.py", line 340, in main
    parser.error('No world paths or region files specified! Use '
  File "C:\Users\lilli\AppData\Local\Programs\Python\Python37\lib\optparse.py", line 1569, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "C:\Users\lilli\AppData\Local\Programs\Python\Python37\lib\optparse.py", line 1559, in exit
    sys.exit(status)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lilli\Downloads\Minecraft-Region-Fixer-0.3.1\Minecraft-Region-Fixer-0.3.1\regionfixer.py", line 587, in <module>
    sys.exit(value)
NameError: name 'value' is not defined

C:\Users\lilli\Downloads\Minecraft-Region-Fixer-0.3.1\Minecraft-Region-Fixer-0.3.1>

**Comment by Fenixin** [comment]
Hello!

That looks like a big in region-fixer code. I going to give it a look.

Since you posted this, have you found a way to make it work?

**Comment by Fenixin** [comment]
I know why it's throwing an exception but I have no idea why it's executing that code when you are clearly pointing out a world folder.

Could you please try something like:

```
python regionfixer.py C:\Users\lilli\AppData\Roaming.minecraft\saves\Copy of 29 4 19 tired
```

This is a desperate test because I have no idea what's going on. In my setup I can make the exception to show up, but not in that way.

**Comment by Fenixin** [comment]
Are you still having this problem?

If so, could you test the following command?

``python regionfixer.py "C:\Users\lilli\AppData\Roaming.minecraft\saves\Copy of 29 4 19 tired"``

If you solved your problem please, tell me how, because I'm lost.

**Comment by DimensionSponge** [comment]
It doesn't appear to be working, sorry :( 
The above says
'python' is not recognized as an internal or external command,
operable program or batch file.
Maybe it's something on my end? I fixed the world with mcedit by the way.
When I remove the python it says this. Without quotations and copying in the filepath it says the same thing.
Usage:
region_fixer [options] <world-path> <other-world-path> ... <region-files> ...

region_fixer: error: No world paths or region files specified! Use --help for a complete list of options.
Traceback (most recent call last):
  File "C:\Users\lilli\Downloads\Minecraft-Region-Fixer-master\Minecraft-Region-Fixer-master\regionfixer.py", line 560, in <module>
    value = main()
  File "C:\Users\lilli\Downloads\Minecraft-Region-Fixer-master\Minecraft-Region-Fixer-master\regionfixer.py", line 340, in main
    parser.error('No world paths or region files specified! Use '
  File "C:\Users\lilli\AppData\Local\Programs\Python\Python37\lib\optparse.py", line 1569, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "C:\Users\lilli\AppData\Local\Programs\Python\Python37\lib\optparse.py", line 1559, in exit
    sys.exit(status)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lilli\Downloads\Minecraft-Region-Fixer-master\Minecraft-Region-Fixer-master\regionfixer.py", line 587, in <module>
    sys.exit(value)
NameError: name 'value' is not defined

C:\Users\lilli\Downloads\Minecraft-Region-Fixer-master\Minecraft-Region-Fixer-master>

**Comment by Fenixin** [comment]
I'm sorry this got forgotten and didn't help you to solve the issue. I'm glad you fixed your world. I'm closing this because is quite old.
